server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO}
          default-label: main
          basedir: config
          searchPaths: config
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://172.18.0.2:8761/eureka/