server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO}
          default-label: main
          basedir: config
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}