server: port:8080

spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/core
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6380
