server:
  port:8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/cori
    username: ssafy
    password: ssafy
  redis:
    host: localhost
    port: 6380
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          jira:
            client-id: ${JIRA_CLIENT}
            client-secret: ${JIRA_SECRET}
            redirect-uri: ${JIRA_CALLBACK}